#!/bin/bash


#First update system
sudo apt update

#enter wait command finish install
wait

#download java run time environment
sudo apt install fontconfig openjdk-17-jre

#enter wait command finish install
wait

#This is the Debian package repository of Jenkins to automate installation and upgrade.
curl -fsSL https://pkg.jenkins.io/debian/jenkins.io-2023.key | sudo tee \/usr/share/keyrings/jenkins-keyring.asc > /dev/null

#Then add a Jenkins apt repository entry
echo deb [signed-by=/usr/share/keyrings/jenkins-keyring.asc] \https://pkg.jenkins.io/debian binary/ | sudo tee \/etc/apt/sources.list.d/jenkins.list > /dev/null

#run update command again  HOw to check for Jenkins package? check to see if this file exists (/etc/apt/sources.list.d/jenkins.list content in file)
sudo apt update

#enter wait command finish install
wait


put in check statement if/else

#install jenkins if found type y
sudo apt install jenkins

#sleep to finish install

#run command to check status of jenkins How to check if it is running? looking for [Active: active (running)]. What to do if its not?
systemctl status jenkins

#exit out of systemctl
q

#how to pull unlock code? Do we use haystack example to find file if this directory changes
sudo cat /var/lib/jenkins/secrets/initialAdminPassword

#copy password
